update yml

diff --git a/.github/workflows/main_whatsapp-chatbot-webhook.yml b/.github/workflows/main_whatsapp-chatbot-webhook.yml
--- a/.github/workflows/main_whatsapp-chatbot-webhook.yml
+++ b/.github/workflows/main_whatsapp-chatbot-webhook.yml
@@ -26,17 +26,17 @@ jobs:
         
       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
 
-      - name: Create startup script
-        run: |
-          echo "#!/bin/bash" > startup.sh
-          echo "if ! command -v ffmpeg &> /dev/null" >> startup.sh
-          echo "then" >> startup.sh
-          echo "    echo 'ffmpeg not found, installing...'" >> startup.sh
-          echo "    apt-get update && apt-get install -y ffmpeg" >> startup.sh
-          echo "else" >> startup.sh
-          echo "    echo 'ffmpeg is already installed'" >> startup.sh
-          echo "fi" >> startup.sh
-          chmod +x startup.sh
+      # - name: Create startup script
+      #   run: |
+      #     echo "#!/bin/bash" > startup.sh
+      #     echo "if ! command -v ffmpeg &> /dev/null" >> startup.sh
+      #     echo "then" >> startup.sh
+      #     echo "    echo 'ffmpeg not found, installing...'" >> startup.sh
+      #     echo "    apt-get update && apt-get install -y ffmpeg" >> startup.sh
+      #     echo "else" >> startup.sh
+      #     echo "    echo 'ffmpeg is already installed'" >> startup.sh
+      #     echo "fi" >> startup.sh
+      #     chmod +x startup.sh
 
       - name: Zip artifact for deployment
         run: |
@@ -80,11 +80,11 @@ jobs:
           slot-name: 'production'
           package: release.zip
 
-      - name: Configure App Service to use startup script
-        run: |
-          az webapp config appsettings set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings WEBSITE_RUN_FROM_PACKAGE=1
-          az webapp config appsettings set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings STARTUP_COMMAND="./startup.sh"
+      # - name: Configure App Service to use startup script
+      #   run: |
+      #     az webapp config appsettings set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings WEBSITE_RUN_FROM_PACKAGE=1
+      #     az webapp config appsettings set --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --settings STARTUP_COMMAND="./startup.sh"
 
-      - name: Restart Azure Web App
-        run: |
-          az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
+      # - name: Restart Azure Web App
+      #   run: |
+      #     az webapp restart --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
